### ISSUE TITLE
Traceback: Unsaved model instance <Bucket> cannot be used in an ORM query

### ISSUE THREAD

**Issue by jschwartzentruber** [MozillaSecurity/FuzzManager#1014]
Observed on production instance:
```
<ip-addr> - user@mozilla.com [07/Oct/2024:02:00:04 +0000] "POST /crashmanager/rest/buckets/?save=true&reassign=true&offset=0 HTTP/1.1" 201 77 "https://fuzzmanager.fuzzing.mozilla.org/crashmanager/signatures/new/?crashid=8252873" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0"
<ip-addr> - user@mozilla.com [07/Oct/2024:02:00:04 +0000] "POST /crashmanager/rest/buckets/?save=true&reassign=true&offset=1000 HTTP/1.1" 500 145 "https://fuzzmanager.fuzzing.mozilla.org/crashmanager/signatures/new/?crashid=8252873" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0"
Internal Server Error: /crashmanager/rest/buckets/
Traceback (most recent call last):
  File "/home/worker/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/worker/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/worker/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/worker/.local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/worker/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/worker/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/worker/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/worker/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/src/server/crashmanager/views.py", line 1401, in create
    return self.__validate(
  File "/src/server/crashmanager/views.py", line 1296, in __validate
    inList, outList, inListCount, outListCount, nextOffset = bucket.reassign(
  File "/src/server/crashmanager/models.py", line 279, in reassign
    CrashEntry.objects.filter(pk__in=updList).update(bucket=self)
  File "/home/worker/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1206, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/worker/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/worker/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/home/worker/.local/lib/python3.10/site-packages/django/db/backends/mysql/compiler.py", line 57, in as_sql
    update_query, update_params = super().as_sql()
  File "/home/worker/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1940, in as_sql
    val = val.prepare_database_save(field)
  File "/home/worker/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1208, in prepare_database_save
    raise ValueError(
ValueError: Unsaved model instance <Bucket: Bucket object (None)> cannot be used in an ORM query.
```

**Comment by jschwartzentruber** [comment]
Fixed in #1015
