### ISSUE TITLE
[EC2SpotManager] Unhandled Error: Invalid AWS credentials

### ISSUE THREAD

**Issue by choller** [MozillaSecurity/FuzzManager#106]
It looks like we don't handle invalid AWS credentials propertly:

```
ERROR:boto:401 Unauthorized
ERROR:boto:<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>27e9e553-1868-49dc-ab13-7e19b5eca163</RequestID></Response>
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "FuzzManager/server/ec2spotmanager/management/common.py", line 44, in wrapper
    method(*args, **options)
  File "FuzzManager/server/ec2spotmanager/management/commands/start_monitoring_daemon.py", line 30, in handle_noargs
    self.check_instance_pools()
  File "FuzzManager/server/ec2spotmanager/management/commands/start_monitoring_daemon.py", line 111, in check_instance_pools
    self.start_pool_instances(instance_pool, config, count=instances_missing)
  File "FuzzManager/server/ec2spotmanager/management/commands/start_monitoring_daemon.py", line 173, in start_pool_instances
    (region, zone, rejected) = self.get_best_region_zone(config)
  File "FuzzManager/server/ec2spotmanager/management/commands/start_monitoring_daemon.py", line 122, in get_best_region_zone
    prices = get_spot_prices(config.ec2_allowed_regions, config.aws_access_key_id, config.aws_secret_access_key, config.ec2_instance_type)
  File "FuzzManager/server/ec2spotmanager/common/prices.py", line 45, in get_spot_prices
    f = get_spot_price_per_region(region, aws_key_id, aws_secret_key, instance_type)
  File "FuzzManager/server/ec2spotmanager/common/prices.py", line 31, in get_spot_price_per_region
    product_description="Linux/UNIX"
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 1420, in get_spot_price_history
    [('item', SpotPriceHistory)], verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1185, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 401 Unauthorized
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>27e9e553-1868-49dc-ab13-7e19b5eca163</RequestID></Response>
```

**Comment by choller** [comment]
This should be handled like all other laniakea/EC2 errors now and cause a fatal message to be added to the pool.
