### ISSUE TITLE
manage.py syncdb fails on migration

### ISSUE THREAD

**Issue by crowell** [MozillaSecurity/FuzzManager#190]
here is the traceback

```
(fuzzer)termina FuzzManager/server ‹master*› » python ./manage.py syncdb
Operations to perform:
  Synchronize unmigrated apps: rest_framework, chartjs
  Apply all migrations: authtoken, sessions, admin, ec2spotmanager, auth, contenttypes, crashmanager
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying authtoken.0001_initial... OK
  Applying crashmanager.0001_initial... OK
  Applying crashmanager.0002_bugzillatemplate_security... OK
  Applying crashmanager.0003_bucket_frequent... OK
  Applying crashmanager.0004_add_tool... OK
  Applying crashmanager.0005_add_user... OK
  Applying crashmanager.0006_user_defaultproviderid... OK
  Applying crashmanager.0007_bugzillatemplate_comment... OK
  Applying crashmanager.0008_crashentry_crashaddressnumeric... OK
  Applying crashmanager.0009_copy_crashaddress... OK
  Applying crashmanager.0010_bugzillatemplate_security_group... OK
  Applying crashmanager.0011_bucket_permanent... OK
  Applying crashmanager.0012_crashentry_cachedcrashinfo... OK
  Applying crashmanager.0013_init_cachedcrashinfo...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 27, in handle_noargs
    call_command("migrate", **options)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 160, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 63, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 97, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 107, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 117, in database_forwards
    self.code(from_state.render(), schema_editor)
  File "/home/jeff/FuzzManager/server/crashmanager/migrations/0013_init_cachedcrashinfo.py", line 8, in create_migration_tool
    for entry in CrashEntry.objects.filter(cachedCrashInfo=None):
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/models/query.py", line 141, in __iter__
    self._fetch_all()
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: crashmanager_crashentry.triagedOnce
```

**Comment by choller** [comment]
Is this a new installation or are you trying to migrate an existing one?

**Comment by choller** [comment]
And can you run `python ./manage.py migrate` to see if the error persists? Thanks!

**Comment by crowell** [comment]
yes it does persist. this is a new installation (in a clean virtualenv).

**Comment by crowell** [comment]
(shown with a clean checkout of master)

```
(fuzzer)termina ~ » git clone https://github.com/MozillaSecurity/FuzzManager.git
Cloning into 'FuzzManager'...
remote: Counting objects: 4956, done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 4956 (delta 46), reused 0 (delta 0), pack-reused 4871
Receiving objects: 100% (4956/4956), 2.76 MiB | 0 bytes/s, done.
Resolving deltas: 100% (3297/3297), done.
Checking connectivity... done.
(fuzzer)termina ~ » cd FuzzManager/server 
(fuzzer)termina FuzzManager/server ‹master› » python ./manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: rest_framework, chartjs
  Apply all migrations: authtoken, sessions, admin, ec2spotmanager, auth, contenttypes, crashmanager
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying authtoken.0001_initial... OK
  Applying crashmanager.0001_initial... OK
  Applying crashmanager.0002_bugzillatemplate_security... OK
  Applying crashmanager.0003_bucket_frequent... OK
  Applying crashmanager.0004_add_tool... OK
  Applying crashmanager.0005_add_user... OK
  Applying crashmanager.0006_user_defaultproviderid... OK
  Applying crashmanager.0007_bugzillatemplate_comment... OK
  Applying crashmanager.0008_crashentry_crashaddressnumeric... OK
  Applying crashmanager.0009_copy_crashaddress... OK
  Applying crashmanager.0010_bugzillatemplate_security_group... OK
  Applying crashmanager.0011_bucket_permanent... OK
  Applying crashmanager.0012_crashentry_cachedcrashinfo... OK
  Applying crashmanager.0013_init_cachedcrashinfo...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 160, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 63, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 97, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 107, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 117, in database_forwards
    self.code(from_state.render(), schema_editor)
  File "/home/jeff/FuzzManager/server/crashmanager/migrations/0013_init_cachedcrashinfo.py", line 8, in create_migration_tool
    for entry in CrashEntry.objects.filter(cachedCrashInfo=None):
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/models/query.py", line 141, in __iter__
    self._fetch_all()
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: crashmanager_crashentry.triagedOnce
```

**Comment by choller** [comment]
I reproduced the problem, this is caused by a recent addition made to the CrashEntry model but I don't fully understand why migration doesn't handle it. You can try this patch as a temporary workaround to get a working installation:

```
diff --git a/server/crashmanager/migrations/0013_init_cachedcrashinfo.py b/server/crashmanager/migrations/0013_init_cachedcrashinfo.py
index b04d76e..41ee794 100644
--- a/server/crashmanager/migrations/0013_init_cachedcrashinfo.py
+++ b/server/crashmanager/migrations/0013_init_cachedcrashinfo.py
@@ -5,8 +5,9 @@ from django.db import migrations
 from crashmanager.models import CrashEntry
 
 def create_migration_tool(apps, schema_editor):
-    for entry in CrashEntry.objects.filter(cachedCrashInfo=None):
-        entry.save(update_fields=['cachedCrashInfo'])
+    pass
+    #for entry in CrashEntry.objects.filter(cachedCrashInfo=None):
+    #    entry.save(update_fields=['cachedCrashInfo'])
 
 class Migration(migrations.Migration):
```


Then re-run syncdb.

**Comment by crowell** [comment]
awesome. that works now. there are still some hurdles to getting the full "funfuzz" setup working, but I'll open issues against those instead of continuing here.

**Comment by crowell** [comment]
opened bug here https://github.com/MozillaSecurity/funfuzz/issues/30

**Comment by choller** [comment]
Thanks! I don't maintain that code (and it doesn't belong to FuzzManager) but I guess my colleagues will take a look soon. If you have your own fuzzers you can also connect them directly to FuzzManager.

**Comment by choller** [comment]
Fixed. The bug here was that we were importing the CrashEntry model directly from crashmanager.models. In migrations, this isn't allowed because then you import the current version of the model, instead of the version that it had at the time of the migration.
