### ISSUE TITLE
ImportError: No module named chartjs

### ISSUE THREAD

**Issue by juneJuly** [MozillaSecurity/FuzzManager#211]
$ python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/Library/Python/2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Python/2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Library/Python/2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named chartjs

============> and my env:
Django==1.9.7
numpy==1.11.0
djangorestframework==3.3.3
requests==2.7.0
lockfile==0.12.2
boto==2.40.0
django-chartjs==1.0

**Comment by juneJuly** [comment]
OK, i fixed this by reinstall all the requirements.

**Comment by choller** [comment]
Thanks for trying out FuzzManager.

If you hit any other road blocks during setup or while initially trying to use it, please let me know. We are using the system in production just fine, but the intial setup is still a little sketchy at some points and not well documented.
