### ISSUE TITLE
[CrashManager, FTB] "AddressSanitizer CHECK failed" should be recognized as a crash for bucketing

### ISSUE THREAD

**Issue by jschwartzentruber** [MozillaSecurity/FuzzManager#270]
We are commonly seeing ASan checks fail in out-of-memory situations. For example:

    ==18625==AddressSanitizer CHECK failed: /builds/slave/moz-toolchain/src/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:183 "((0 && "unable to mmap")) != (0)" (0x0, 0x0)
        #0 0x4bbf1d in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /builds/slave/moz-toolchain/src/llvm/projects/compiler-rt/lib/asan/asan_rtl.cc:67:3
        #1 0x4bfe4f in CheckFailed /builds/slave/moz-toolchain/src/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:159:5
        #2 0x4bfe4f in __sanitizer::ReportMmapFailureAndDie(unsigned long, char const*, char const*, int, bool) /builds/slave/moz-toolchain/src/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:183

This should be recognized as a crash so signatures can be created for these.

**Comment by jschwartzentruber** [comment]
Closing per conversation with @choller. This is not a fuzzing result but an error in the toolchain which should be fixed.
