### ISSUE TITLE
[EC2SpotManager] Traceback in EC2SpotManager daemon

### ISSUE THREAD

**Issue by jschwartzentruber** [MozillaSecurity/FuzzManager#339]
Traceback observed on the production server during normal operation:

```
ubuntu@host:/srv/fuzzmanager/FuzzManager/server$ python manage.py start_monitoring_daemon --settings=server.settings_nondebug
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/srv/fuzzmanager/FuzzManager/server/ec2spotmanager/management/common.py", line 44, in wrapper
    method(*args, **options)
  File "/srv/fuzzmanager/FuzzManager/server/ec2spotmanager/management/commands/start_monitoring_daemon.py", line 48, in handle_noargs
    self.check_instance_pools()
  File "/srv/fuzzmanager/FuzzManager/server/ec2spotmanager/management/commands/start_monitoring_daemon.py", line 153, in check_instance_pools
    self.start_pool_instances(instance_pool, config, count=instances_missing)
  File "/srv/fuzzmanager/FuzzManager/server/ec2spotmanager/management/commands/start_monitoring_daemon.py", line 261, in start_pool_instances
    instance.save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 591, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 619, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 700, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 733, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 128, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`fuzzmanager`.`ec2spotmanager_instance`, CONSTRAINT `ec2sp_pool_id_xxxxxxxxxxxxxxxx_fk_ec2spotmanager_instancepool_id` FOREIGN KEY (`pool_id`) REFERENCES `ec2spotmanager_instancepool` (`id`))')
```

**Comment by jschwartzentruber** [comment]
A helpful user was testing the django110 branch test deployment and reproduced this issue where I was able to get the coinciding access log to show the timeline:

Apache access log:
```
 - twsmith [02/Oct/2017:16:24:53 +0000] "GET /ec2spotmanager/pools/create/ HTTP/1.1" 200 2802 "https://fm-test.domain/ec2spotmanager/pools/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:24:57 +0000] "POST /ec2spotmanager/pools/create/ HTTP/1.1" 302 229 "https://fm-test.domain/ec2spotmanager/pools/create/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:24:57 +0000] "GET /ec2spotmanager/pools/3/ HTTP/1.1" 200 3047 "https://fm-test.domain/ec2spotmanager/pools/create/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:00 +0000] "GET /ec2spotmanager/pools/3/delete/ HTTP/1.1" 200 2761 "https://fm-test.domain/ec2spotmanager/pools/3/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:09 +0000] "GET /ec2spotmanager/pools/ HTTP/1.1" 200 2800 "https://fm-test.domain/crashmanager/usersettings/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:14 +0000] "GET /ec2spotmanager/pools/3/ HTTP/1.1" 200 3047 "https://fm-test.domain/ec2spotmanager/pools/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:15 +0000] "GET /ec2spotmanager/pools/3/enable/ HTTP/1.1" 200 2807 "https://fm-test.domain/ec2spotmanager/pools/3/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:16 +0000] "POST /ec2spotmanager/pools/3/enable/ HTTP/1.1" 302 229 "https://fm-test.domain/ec2spotmanager/pools/3/enable/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:17 +0000] "GET /ec2spotmanager/pools/3/ HTTP/1.1" 200 3062 "https://fm-test.domain/ec2spotmanager/pools/3/enable/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:19 +0000] "GET /ec2spotmanager/pools/3/cycle/ HTTP/1.1" 200 2826 "https://fm-test.domain/ec2spotmanager/pools/3/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:20 +0000] "POST /ec2spotmanager/pools/3/cycle/ HTTP/1.1" 302 229 "https://fm-test.domain/ec2spotmanager/pools/3/cycle/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:21 +0000] "GET /ec2spotmanager/pools/3/ HTTP/1.1" 200 3062 "https://fm-test.domain/ec2spotmanager/pools/3/cycle/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:22 +0000] "GET /ec2spotmanager/pools/3/disable/ HTTP/1.1" 200 2817 "https://fm-test.domain/ec2spotmanager/pools/3/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:24 +0000] "POST /ec2spotmanager/pools/3/disable/ HTTP/1.1" 302 229 "https://fm-test.domain/ec2spotmanager/pools/3/disable/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:24 +0000] "GET /ec2spotmanager/pools/3/ HTTP/1.1" 200 3073 "https://fm-test.domain/ec2spotmanager/pools/3/disable/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:28 +0000] "GET /ec2spotmanager/pools/3/cycle/ HTTP/1.1" 200 2428 "https://fm-test.domain/ec2spotmanager/pools/3/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:31 +0000] "GET /ec2spotmanager/pools/3/delete/ HTTP/1.1" 200 2760 "https://fm-test.domain/ec2spotmanager/pools/3/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:33 +0000] "POST /ec2spotmanager/pools/3/delete/ HTTP/1.1" 302 227 "https://fm-test.domain/ec2spotmanager/pools/3/delete/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:33 +0000] "GET /ec2spotmanager/pools/ HTTP/1.1" 200 2766 "https://fm-test.domain/ec2spotmanager/pools/3/delete/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
 - twsmith [02/Oct/2017:16:25:37 +0000] "GET /ec2spotmanager/pools/3/delete/ HTTP/1.1" 404 1969 "https://fm-test.domain/ec2spotmanager/pools/3/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
```

FM monitor daemon log:
```
Oct 02 16:25:21 fm-monitor[14067]: INFO:ec2spotmanager:[Pool 3] Needs to be cycled, terminating all instances...
Oct 02 16:25:21 fm-monitor[14067]: INFO:ec2spotmanager:[Pool 3] Termination complete.
Oct 02 16:25:21 fm-monitor[14067]: INFO:ec2spotmanager:[Pool 3] Needs 1 more instances, starting...
Oct 02 16:25:36 fm-monitor[14067]: Traceback (most recent call last):
Oct 02 16:25:36 fm-monitor[14067]:   File "manage.py", line 10, in <module>
Oct 02 16:25:36 fm-monitor[14067]:     execute_from_command_line(sys.argv)
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
Oct 02 16:25:36 fm-monitor[14067]:     utility.execute()
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 355, in execute
Oct 02 16:25:36 fm-monitor[14067]:     self.fetch_command(subcommand).run_from_argv(self.argv)
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
Oct 02 16:25:36 fm-monitor[14067]:     self.execute(*args, **cmd_options)
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
Oct 02 16:25:36 fm-monitor[14067]:     output = self.handle(*args, **options)
Oct 02 16:25:36 fm-monitor[14067]:   File "/srv/fm-test.domain/FuzzManager/server/ec2spotmanager/management/common.py", line 44, in wrapper
Oct 02 16:25:36 fm-monitor[14067]:     method(*args, **options)
Oct 02 16:25:36 fm-monitor[14067]:   File "/srv/fm-test.domain/FuzzManager/server/ec2spotmanager/management/commands/start_monitoring_daemon.py", line 51, in handle
Oct 02 16:25:36 fm-monitor[14067]:     self.check_instance_pools()
Oct 02 16:25:36 fm-monitor[14067]:   File "/srv/fm-test.domain/FuzzManager/server/ec2spotmanager/management/commands/start_monitoring_daemon.py", line 156, in check_instance_pools
Oct 02 16:25:36 fm-monitor[14067]:     self.start_pool_instances(instance_pool, config, count=instances_missing)
Oct 02 16:25:36 fm-monitor[14067]:   File "/srv/fm-test.domain/FuzzManager/server/ec2spotmanager/management/commands/start_monitoring_daemon.py", line 264, in start_pool_instances
Oct 02 16:25:36 fm-monitor[14067]:     instance.save()
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 806, in save
Oct 02 16:25:36 fm-monitor[14067]:     force_update=force_update, update_fields=update_fields)
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 836, in save_base
Oct 02 16:25:36 fm-monitor[14067]:     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 922, in _save_table
Oct 02 16:25:36 fm-monitor[14067]:     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 961, in _do_insert
Oct 02 16:25:36 fm-monitor[14067]:     using=using, raw=raw)
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
Oct 02 16:25:36 fm-monitor[14067]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1063, in _insert
Oct 02 16:25:36 fm-monitor[14067]:     return query.get_compiler(using=using).execute_sql(return_id)
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1099, in execute_sql
Oct 02 16:25:36 fm-monitor[14067]:     cursor.execute(sql, params)
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
Oct 02 16:25:36 fm-monitor[14067]:     return self.cursor.execute(sql, params)
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
Oct 02 16:25:36 fm-monitor[14067]:     six.reraise(dj_exc_type, dj_exc_value, traceback)
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
Oct 02 16:25:36 fm-monitor[14067]:     return self.cursor.execute(sql, params)
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 101, in execute
Oct 02 16:25:36 fm-monitor[14067]:     return self.cursor.execute(query, args)
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
Oct 02 16:25:36 fm-monitor[14067]:     self.errorhandler(self, exc, value)
Oct 02 16:25:36 fm-monitor[14067]:   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
Oct 02 16:25:36 fm-monitor[14067]:     raise errorvalue
Oct 02 16:25:36 fm-monitor[14067]: django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`fuzzmanager`.`ec2spotmanager_instance`, CONSTRAINT `ec2spotmanager_insta_pool_id_c5aeb315_fk_ec2spotma` FOREIGN KEY (`pool_id`) REFERENCES `ec2spotmanager_instancepool` (`id`))')
```

**Comment by jschwartzentruber** [comment]
Closing as we haven't seen this since the daemon was moved to celery.
