### ISSUE TITLE
mysql python ./manage.py migrate django.db.utils.OperationalError:

### ISSUE THREAD

**Issue by kkuehl** [MozillaSecurity/FuzzManager#564]
python ./manage.py migrate
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, covmanager, crashmanager, ec2spotmanager, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying crashmanager.0001_initial... OK
  Applying crashmanager.0002_bugzillatemplate_security... OK
  Applying crashmanager.0003_bucket_frequent... OK
  Applying crashmanager.0004_add_tool... OK
  Applying crashmanager.0005_add_user... OK
  Applying crashmanager.0006_user_defaultproviderid... OK
  Applying crashmanager.0007_bugzillatemplate_comment... OK
  Applying crashmanager.0008_crashentry_crashaddressnumeric... OK
  Applying crashmanager.0009_copy_crashaddress... OK
  Applying crashmanager.0010_bugzillatemplate_security_group... OK
  Applying crashmanager.0011_bucket_permanent... OK
  Applying crashmanager.0012_crashentry_cachedcrashinfo... OK
  Applying crashmanager.0013_init_cachedcrashinfo... OK
  Applying crashmanager.0014_bugzillatemplate_testcase_filename... OK
  Applying crashmanager.0015_crashentry_triagedonce... OK
  Applying crashmanager.0016_auto_20160308_1500... OK
  Applying crashmanager.0017_user_restricted... OK
  Applying crashmanager.0018_auto_20170620_1503... OK
  Applying covmanager.0001_initial... OK
  Applying covmanager.0002_increase_collection_filename_length... OK
  Applying covmanager.0003_collection_file_optional... OK
  Applying covmanager.0004_reportconfiguration_reportsummary... OK
  Applying covmanager.0005_report... OK
  Applying crashmanager.0019_bucket_optimizedsignature... OK
  Applying crashmanager.0020_add_app_permissions... OK
  Applying ec2spotmanager.0001_initial... OK
  Applying ec2spotmanager.0002_instancestatusentry_poolstatusentry... OK
  Applying ec2spotmanager.0003_auto_20150505_1225... OK
  Applying ec2spotmanager.0004_auto_20150507_1311... OK
  Applying ec2spotmanager.0005_auto_20150520_1517... OK
  Applying ec2spotmanager.0006_auto_20150625_2050... OK
  Applying ec2spotmanager.0007_instance_type_to_list... OK
  Applying ec2spotmanager.0008_remove_aws_creds... OK
  Applying ec2spotmanager.0009_add_instance_size... OK
  Applying ec2spotmanager.0010_extend_instance_types... OK
  Applying ec2spotmanager.0011_auto_20181012_0011... OK
  Applying ec2spotmanager.0012_add_instance_provider... OK
  Applying ec2spotmanager.0013_add_gce_fields...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/fields.py", line 88, in database_forwards
    field,
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/schema.py", line 48, in add_field
    super(DatabaseSchemaEditor, self).add_field(model, field)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 445, in add_field
    self.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 136, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
django.db.utils.OperationalError: (1118, 'Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs')

**Comment by jschwartzentruber** [comment]
I'm not sure why this happened, but I hope #592 will help.
