### ISSUE TITLE
CrashManager migration fails to apply

### ISSUE THREAD

**Issue by jschwartzentruber** [MozillaSecurity/FuzzManager#915]
Latest crashmanager migration does not apply.

The traceback was out of my scrollback before I could save it, but the error was in `server/crashmanager/migrations/0011_alter_user_options.py`  in `grant_existing_perms` because the permission object does not exist yet when the migration is run.

I manually applied by commenting out the`RunPython` migration, running `manage.py migrate`, and then running the logic contained in `grant_existing_perms` in a `manage.py shell`.

**Comment by jschwartzentruber** [comment]
Traceback reproduced on staging.
```
  Applying crashmanager.0011_alter_user_options...Traceback (most recent call last):
  File "/src/server/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/worker/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/worker/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/worker/.local/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/worker/.local/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/home/worker/.local/lib/python3.10/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/worker/.local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
  File "/home/worker/.local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/home/worker/.local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/home/worker/.local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/worker/.local/lib/python3.10/site-packages/django/db/migrations/migration.py", line 125, in apply
    operation.database_forwards(
  File "/home/worker/.local/lib/python3.10/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/src/server/crashmanager/migrations/0011_alter_user_options.py", line 20, in grant_existing_perms
    Permission.objects.get(
  File "/home/worker/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/worker/.local/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Permission.DoesNotExist: Permission matching query does not exist.
```
